export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'

export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GET_ACCOUNT_USERS_SUCCESS = 'GET_ACCOUNT_USERS_SUCCESS'

export const SET_FLOW_STEP = 'SET_FLOW_STEP'

export const GET_WORKFLOW_LIST_SUCCESS = 'GET_WORKFLOW_LIST_SUCCESS'

export const CREATE_WORKFLOW_SUCCESS = 'CREATE_WORKFLOW_SUCCESS'

export const EMPTY_WORKFLOW_XML = 'EMPTY_WORKFLOW_XML'

export const DELETE_WORKFLOW_SUCCESS = 'DELETE_WORKFLOW_SUCCESS'
export const GET_WORKFLOW_RELATED_SUCCESS = 'GET_WORKFLOW_RELATED_SUCCESS'

export const GET_WORKFLOW_DETAIL_SUCCESS = 'GET_WORKFLOW_DETAIL_SUCCESS'

export const GET_WORKFLOW_NODE_LIST_SUCCESS = 'GET_WORKFLOW_NODE_LIST_SUCCESS'

export const GET_PROCESS_SUCCESS = 'GET_PROCESS_SUCCESS'

export const GET_PROCESS_POSITIONS_SUCCESS = 'GET_PROCESS_POSITIONS_SUCCESS'

export const UPDATE_WORKFLOW_NODES_SUCCESS = 'UPDATE_WORKFLOW_NODES_SUCCESS'

export const GET_WORKFLOW_DOC_LIST_SUCCESS = 'GET_WORKFLOW_DOC_LIST_SUCCESS'

export const DELETE_WORKFLOW_DOC = 'DELETE_WORKFLOW_DOC'

export const GET_WORKFLOW_ROLE_LIST_SUCCESS = 'GET_WORKFLOW_ROLE_LIST_SUCCESS'

export const GET_WORKFLOW_ROLE_ASSIGN_SUCCESS = 'GET_WORKFLOW_ROLE_ASSIGN_SUCCESS'

export const GET_WORKFLOW_ROLE_IMG_LIST_SUCCESS = 'GET_WORKFLOW_ROLE_IMG_LIST_SUCCESS'

export const DELETE_WORKFLOW_ROLES = 'DELETE_WORKFLOW_ROLES'

export const GET_WORKFLOW_ROLE_ALLOCATION = 'GET_WORKFLOW_ROLE_ALLOCATION'

export const GET_WORKFLOW_ACTIONS_SUCCESS = 'GET_WORKFLOW_ACTIONS_SUCCESS'

export const GET_WORKFLOW_ROLE_ACTIONS_SUCCESS = 'GET_WORKFLOW_ROLE_ACTIONS_SUCCESS'

export const QUERY_WORKFLOW_TRANS_SUCCESS = 'QUERY_WORKFLOW_TRANS_SUCCESS'

export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS'

export const SELECT_PROJECT_TO_SET = 'SELECT_PROJECT_TO_SET'

export const GET_PROJECT_DETAIL_SUCCESS = 'GET_PROJECT_DETAIL_SUCCESS'

export const GET_PROJECT_ROLES_DETAIL_SUCCESS = 'GET_PROJECT_ROLES_DETAIL_SUCCESS'

export const GET_PROJECT_DOCS_DETAIL_SUCCESS = 'GET_PROJECT_DOCS_DETAIL_SUCCESS'

export const GET_PROJECT_RELATED_SUCCESS = 'GET_PROJECT_RELATED_SUCCESS'

export const GET_TEAM_LIST_SUCCESS = 'GET_TEAM_LIST_SUCCESS'

export const GET_EXPERIMENT_LIST_SUCCESS = 'GET_EXPERIMENT_LIST_SUCCESS'

export const GET_EXPERIMENT_DETAIL_SUCCESS = 'GET_EXPERIMENT_DETAIL_SUCCESS'

export const GET_MYTEAM_LIST_SUCCESS = 'GET_MYTEAM_LIST_SUCCESS'

export const GET_OTHERTEAM_LIST_SUCCESS = 'GET_OTHERTEAM_LIST_SUCCESS'

export const GET_COURSE_CLASS_LIST_SUCCESS = 'GET_COURSE_CLASS_LIST_SUCCESS'

export const GET_COURSE_LIST_SUCCESS = 'GET_COURSE_LIST_SUCCESS'

export const GET_MEMBER_LIST_SUCCESS = 'GET_MEMBER_LIST_SUCCESS'

export const POST_MESSAGE = 'POST_MESSAGE'

export const SET_EXP_PARAM = 'SET_EXP_PARAM'

export const GET_EXPERIMENT_ROLE_IN_LIST_SUCCESS = 'GET_EXPERIMENT_ROLE_IN_LIST_SUCCESS'
export const GET_EXPERIMENT_ROLE_OUT_LIST_SUCCESS = 'GET_EXPERIMENT_ROLE_OUT_LIST_SUCCESS'

export const GET_EXPERIMENT_NODE_DETAIL_SUCCESS = 'GET_EXPERIMENT_NODE_DETAIL_SUCCESS'
export const GET_EXPERIMENT_NODE_DOCS_SUCCESS = 'GET_EXPERIMENT_NODE_DOCS_SUCCESS'
export const GET_EXPERIMENT_NODE_FUNCTION_SUCCESS = 'GET_EXPERIMENT_NODE_FUNCTION_SUCCESS'
export const GET_EXPERIMENT_NOTE_LIST_SUCCESS = 'GET_EXPERIMENT_NOTE_LIST_SUCCESS'
export const GET_EXPERIMENT_RESULTS_SUCCESS = 'GET_EXPERIMENT_RESULTS_SUCCESS'
export const GET_EXPERIMENT_ROLE_STATUS_SUCCESS = 'GET_EXPERIMENT_ROLE_STATUS_SUCCESS'
export const GET_EXPERIMENT_NODE_MESSAGES_SUCCESS = 'GET_EXPERIMENT_NODE_MESSAGES_SUCCESS'

export const DISPATCH_FLASH_ACTION = 'DISPATCH_FLASH_ACTION'

export const INIT_WEBIM_CONN = 'INIT_WEBIM_CONN'

export const PUSH_MESSAGE_SUCCESS = 'PUSH_MESSAGE_SUCCESS'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'

export const EMPTY_MESSAGE_SUCCESS = 'EMPTY_MESSAGE_SUCCESS'

export const GET_EXPERIMENT_DISPLAY_LIST_SUCCESS = 'GET_EXPERIMENT_DISPLAY_LIST_SUCCESS'

export const GET_EXPERIMENT_DISPLAY_APPLY_SUCCESS = 'GET_EXPERIMENT_DISPLAY_APPLY_SUCCESS'

export const GET_EXPERIMENT_TEMPLATES_SUCCESS = 'GET_EXPERIMENT_TEMPLATES_SUCCESS'

export const GENERATE_EXPERIMENT_REPORT_SUCCESS = 'GENERATE_EXPERIMENT_REPORT_SUCCESS'

export const GET_EXPERIMENT_EXPERIENCE_SUCCESS = 'GET_EXPERIMENT_EXPERIENCE_SUCCESS'

export const GET_EXPERIMENT_PROJECT_TIPS_SUCCESS = 'GET_EXPERIMENT_PROJECT_TIPS_SUCCESS'

export const SET_CURRENT_ROLE = 'SET_CURRENT_ROLE'

export const START_ROLE_BANNED = 'START_ROLE_BANNED'

export const SHOW_TRANS_MODAL = 'SHOW_TRANS_MODAL'

export const HIDE_TRANS_MODAL = 'HIDE_TRANS_MODAL'

export const EMPTY_ACTION_CMD = 'EMPTY_ACTION_CMD'

export const SEND_EXPERIENCE = 'SEND_EXPERIENCE'

export const UPDATE_VOTE_STATUS = 'UPDATE_VOTE_STATUS'

export const START_BANNED = 'START_BANNED'

export const UPDATE_USER_ROLES = 'UPDATE_USER_ROLES'

export const QUERY_VOTE_STATUS_SUCCESS = 'QUERY_VOTE_STATUS_SUCCESS'

export const SET_PERMISSION = 'SET_PERMISSION'
